config/routes.rb
Exposition::Engine.routes.draw do
  namespace :admin do
    resources :posts
    resources :tags
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    get    'logout'  => 'sessions#destroy'
  end

  resources :posts, only: [:show]
  resources :tags, only: [:show]

  root to: 'posts#index'
end

app/controllers/exposition/admin/sessions_controller.rb
module Exposition
  class Admin::SessionsController < Admin::AdminController
    skip_before_action :authorize, only: [:new, :create]

    def new
    end

    def create
      permitted = params.require(:session).permit([:email, :password])
      user = User.find_by(email: permitted[:email].downcase)
      if user && user.authenticate(permitted[:password])
        # Log the user in and redirect to the user's show page.

        user.set_encrypted_remember_token!
        session[:user_id] = user.id
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
        redirect_to admin_posts_path
      else
        flash.now[:error] = t("sessions.failed_login")
        render 'new'
      end
    end

    def destroy
      session.delete(:user_id)
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
      redirect_to root_url
    end
  end
end

app/helpers/exposition/layout_header_helper.rb
module Exposition
  module LayoutHeaderHelper
    def title(title)
      content_for(:title, title.to_s)
    end

    def page_description(description)
      content_for(:page_description, description.to_s)
    end
  end
end

app/helpers/exposition/tag_helper.rb
module Exposition
  module TagHelper
    def display_tags_for(taggable)
      taggable_type = taggable.class.name.underscore.to_sym
      draw_tag_markup(tags: taggable.tags, taggable_type: taggable_type)
    end

    private

    def draw_tag_markup(tags:, taggable_type:)
      content_tag(:div, class: 'tags') do
        draw_tags(tags: tags, taggable_type: taggable_type)
      end
    end

    def draw_tags(tags:, taggable_type:)
      rendered_tags = ''

      if tags.any?
        tags.each do |tag|
          rendered_tags << content_tag(:span) do
            draw_tag_url(tag: tag, taggable_type: taggable_type)
          end
        end
      end

      return rendered_tags.html_safe
    end

    def draw_tag_url(tag:, taggable_type:)
      link_to(tag.label, exposition.tag_path(tag, type: taggable_type))
    end
  end
end

app/views/exposition/admin/posts/edit.html.haml
%section.edit-post
  %h2= "Editing Post: #{@post.title}"
  = form_for @post, url: admin_post_path(@post), method: :patch do |f|
    = render partial: 'exposition/admin/shared/error_handler', locals: { model: @post }
    = render partial: 'form_fields', locals: { form: f }

app/views/exposition/admin/posts/index.html.haml
%section.posts
  .admin-title-header
    %h2 Posts
    = link_to "Add New", exposition.new_admin_post_path
  %table 
    %thead
      %tr
        %th Title
        %th Article
        %th Author
        %th Slug
        %th Tags
        %th Manage
    %tbody
      - @posts.each do |post|
        %tr.post{class: "#{post.css_classes}"}
          %td= "#{post.title}"
          %td= truncate(post.summary, length: 40, separator: ' ')
          %td= "#{post.author.name}"
          %td= "#{post.slug}"
          %td= "#{post.tags.to_a.to_sentence}"
          %td= link_to "Edit", exposition.edit_admin_post_path(post)
  = paginate @posts

app/views/exposition/admin/posts/new.html.haml
%section.new-post
  .admin-title-header
    %h2 New Post
    = link_to "Back to Posts", admin_posts_path
  = form_for @post, url: admin_posts_path, method: :post do |f|
    = render partial: 'exposition/admin/shared/error_handler', locals: { model: @post }
    = render partial: 'form_fields', locals: { form: f }

app/views/exposition/admin/shared/_error_handler.html.haml
- if model.errors.any?
  #error-explanation
    %h4
      = pluralize(model.errors.count, "error")
      prohibited this post from being saved:
    %ul
      - model.errors.full_messages.each do |msg|
        %li= msg

app/views/exposition/admin/tags/edit.html.haml
%section.new-tag
  .admin-title-header
    %h2 Edit Tag
    = link_to "Back to Tags", admin_tags_path
  = form_for @tag, url: admin_tag_path(@tag), method: :patch do |f|
    = render partial: 'exposition/admin/shared/error_handler', locals: { model: @tag }
    %p
      = f.label :label
      = f.text_field :label
    %p= f.submit

app/views/exposition/admin/tags/new.html.haml
%section.new-tag
  .admin-title-header
    %h2 New Tag
    = link_to "Back to Tags", admin_tags_path
  = form_for @tag, url: admin_tags_path, method: :post do |f|
    = render partial: 'exposition/admin/shared/error_handler', locals: { model: @tag }
    %p
      = f.label :label
      = f.text_field :label
    %p= f.submit

app/views/exposition/posts/_post.html.haml
%article
  %time= "Published #{l(post.published_at.to_date, format: :long)}"
  .content.summary
    %h2= link_to(post.title, post)
    = preserve do
      = markdown_to_html(post.summary)
  %section.info
    = render 'exposition/posts/tags', tags: post.tags

app/views/exposition/posts/_tags.html.haml
.tags
  - if tags.any?
    - tags.each do |tag|
      %span>= link_to tag.label, tag
  - else
    %span.empty Not tagged

app/views/exposition/posts/index.html.haml
.posts.main-content
  - unless @posts.empty?
    = render @posts
  -else
    %section.no-posts
      %p= t('posts.index.no_posts_warning')

  = paginate @posts

app/views/exposition/posts/show.html.haml
- @post.title
- @post.summary

%article.post.main-content
  %section.content
    %h2= @post.title
    = preserve do
      = markdown_to_html(@post.body)

app/views/exposition/tags/show.html.haml
.posts.main-content
  - unless @taggables.empty?
    = render @taggables
  -else
    %section.no-posts
      %p= t('posts.index.no_posts_warning')

app/views/layouts/exposition/admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Exposition
    = stylesheet_link_tag 'exposition/admin/application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.admin
      %ul
        %li= link_to "Posts", exposition.admin_posts_path
        %li= link_to "Tags", exposition.admin_tags_path
      - if logged_in?
        %ul.login
          %li= link_to current_user.name, exposition.admin_posts_path
          %li= link_to t('sessions.destroy'), exposition.admin_logout_path
    - if flash.any?
      .flashes
        - user_facing_flashes.each do |key, value|
          %div{:class => "flash-#{key}"}= value
    = yield

app/views/layouts/exposition/application.html.haml
<!doctype html>
%html
  %head
    %title= content_for(:title) || t('title')
    %meta{"http-equiv" => "x-ua-compatible", content: "ie=edge"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0, maximum-scale=1.0"}
    %meta{charset: "utf-8"}
    %meta{name: "description", content: (content_for(:page_description) || t('page_description'))}
    %meta{name: "robots", content: "index,follow,noodp"}
    %meta{name: "generator", content: "Exposition"}
    %meta{name: "subject", content: t('site_subject')}
    %base{href: request.base_url}
    = csrf_meta_tags
  %body
    %header
      %nav
        %h1= link_to t('title'), '/'
        %ul.menu
          %li= link_to 'Static Page', '#'
    = yield

    %footer
      .info
        %p= "By #{t('owner')}"